defaults: &defaults
  working_directory: ~/repo
  environment:
    JRUBY_OPTS: --2.0 -J-Xmx1024M
    RAILS_ENV: test
    DB_NAME: kaui

version: 2
jobs:
  build-ruby-2.4.2:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
    steps:
      - checkout
      - restore_cache:
          key: v5-dependencies-ruby-2.4.2-{{ .Branch }}-{{ checksum "kaui.gemspec" }}
      - run:
          name: Install gem dependencies
          command: |
            source /usr/share/rvm/scripts/rvm
            rvm use ruby-2.4.2
            bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - save_cache:
          paths:
            - Gemfile.lock
            - .bundle
            - vendor/bundle
          key: v5-dependencies-ruby-2.4.2-{{ .Branch }}-{{ checksum "kaui.gemspec" }}

  test-mysql-ruby-2.4.2:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
      - image: killbill/killbill:0.19.19
        environment:
        - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
        - KILLBILL_DAO_URL=jdbc:mysql://127.0.0.1:3306/killbill
        - KILLBILL_DAO_USER=root
        - KILLBILL_DAO_PASSWORD=root
        - KILLBILL_SERVER_TEST_MODE=true
        - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
        - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
      - image: killbill/mariadb:0.19
        environment:
        - MYSQL_ROOT_PASSWORD=root
    steps:
      - checkout
      - restore_cache:
          key: v5-dependencies-ruby-2.4.2-{{ .Branch }}-{{ checksum "kaui.gemspec" }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until mysqladmin ping -h 127.0.0.1 -u root --password=root --silent; do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            source /usr/share/rvm/scripts/rvm
            rvm use ruby-2.4.2
            DB_ADAPTER=mysql2 DB_USER='root' DB_PASSWORD='root' DB_PORT=3306 bundle exec rails db:migrate
            DB_ADAPTER=mysql2 DB_USER='root' DB_PASSWORD='root' DB_PORT=3306 bundle exec rails t -w
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  test-postgresql-ruby-2.4.2:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
      - image: killbill/killbill:0.19.19
        environment:
        - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
        - KILLBILL_DAO_URL=jdbc:postgresql://127.0.0.1:5432/killbill
        - KILLBILL_DAO_USER=postgres
        - KILLBILL_DAO_PASSWORD=postgres
        - KILLBILL_SERVER_TEST_MODE=true
        - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
        - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
      - image: killbill/postgresql:0.19
        environment:
        - POSTGRES_PASSWORD=postgres
    steps:
      - checkout
      - restore_cache:
          key: v5-dependencies-ruby-2.4.2-{{ .Branch }}-{{ checksum "kaui.gemspec" }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until $(psql -h 127.0.0.1 -U postgres -p 5432 -l > /dev/null); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            source /usr/share/rvm/scripts/rvm
            rvm use ruby-2.4.2
            DB_ADAPTER=postgresql DB_USER='postgres' DB_PASSWORD='postgres' DB_PORT=5432 bundle exec rails db:migrate
            DB_ADAPTER=postgresql DB_USER='postgres' DB_PASSWORD='postgres' DB_PORT=5432 bundle exec rails t -w
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  build-jruby-9.1.14.0:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
    steps:
      - checkout
      - restore_cache:
          key: v5-dependencies-jruby-9.1.14.0-{{ .Branch }}-{{ checksum "kaui.gemspec" }}
      - run:
          name: Install gem dependencies
          command: |
            source /usr/share/rvm/scripts/rvm
            rvm use jruby-9.1.14.0
            bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - save_cache:
          paths:
            - Gemfile.lock
            - .bundle
            - vendor/bundle
          key: v5-dependencies-jruby-9.1.14.0-{{ .Branch }}-{{ checksum "kaui.gemspec" }}

  test-mariadb-jruby-9.1.14.0:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
      - image: killbill/killbill:0.19.19
        environment:
        - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
        - KILLBILL_DAO_URL=jdbc:mysql://127.0.0.1:3306/killbill
        - KILLBILL_DAO_USER=root
        - KILLBILL_DAO_PASSWORD=root
        - KILLBILL_SERVER_TEST_MODE=true
        - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
        - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
      - image: killbill/mariadb:0.19
        environment:
        - MYSQL_ROOT_PASSWORD=root
    steps:
      - checkout
      - restore_cache:
          key: v5-dependencies-jruby-9.1.14.0-{{ .Branch }}-{{ checksum "kaui.gemspec" }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until mysqladmin ping -h 127.0.0.1 -u root --password=root --silent; do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            source /usr/share/rvm/scripts/rvm
            rvm use jruby-9.1.14.0
            DB_ADAPTER=mariadb DB_USER='root' DB_PASSWORD='root' DB_PORT=3306 bundle exec rails db:migrate
            DB_ADAPTER=mariadb DB_USER='root' DB_PASSWORD='root' DB_PORT=3306 bundle exec rails t -w
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  test-mysql-jruby-9.1.14.0:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
      - image: killbill/killbill:0.19.19
        environment:
        - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
        - KILLBILL_DAO_URL=jdbc:mysql://127.0.0.1:3306/killbill
        - KILLBILL_DAO_USER=root
        - KILLBILL_DAO_PASSWORD=root
        - KILLBILL_SERVER_TEST_MODE=true
        - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
        - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
      - image: killbill/mariadb:0.19
        environment:
        - MYSQL_ROOT_PASSWORD=root
    steps:
      - checkout
      - restore_cache:
          key: v5-dependencies-jruby-9.1.14.0-{{ .Branch }}-{{ checksum "kaui.gemspec" }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until mysqladmin ping -h 127.0.0.1 -u root --password=root --silent; do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            source /usr/share/rvm/scripts/rvm
            rvm use jruby-9.1.14.0
            DB_ADAPTER=mysql2 DB_USER='root' DB_PASSWORD='root' DB_PORT=3306 bundle exec rails db:migrate
            DB_ADAPTER=mysql2 DB_USER='root' DB_PASSWORD='root' DB_PORT=3306 bundle exec rails t -w
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  test-postgresql-jruby-9.1.14.0:
    <<: *defaults
    docker:
      - image: killbill/kbbuild:0.5.0
      - image: killbill/killbill:0.19.19
        environment:
        - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
        - KILLBILL_DAO_URL=jdbc:postgresql://127.0.0.1:5432/killbill
        - KILLBILL_DAO_USER=postgres
        - KILLBILL_DAO_PASSWORD=postgres
        - KILLBILL_SERVER_TEST_MODE=true
        - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
        - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
      - image: killbill/postgresql:0.19
        environment:
        - POSTGRES_PASSWORD=postgres
    steps:
      - checkout
      - restore_cache:
          key: v5-dependencies-jruby-9.1.14.0-{{ .Branch }}-{{ checksum "kaui.gemspec" }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until $(psql -h 127.0.0.1 -U postgres -p 5432 -l > /dev/null); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            source /usr/share/rvm/scripts/rvm
            rvm use jruby-9.1.14.0
            DB_ADAPTER=postgresql DB_USER='postgres' DB_PASSWORD='postgres' DB_PORT=5432 bundle exec rails db:migrate
            DB_ADAPTER=postgresql DB_USER='postgres' DB_PASSWORD='postgres' DB_PORT=5432 bundle exec rails t -w
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      # Kaui and other gems
      - build-ruby-2.4.2
      # Self-contained Kaui
      - build-jruby-9.1.14.0
      - test-mysql-ruby-2.4.2:
          requires:
            - build-ruby-2.4.2
      - test-postgresql-ruby-2.4.2:
          requires:
            - build-ruby-2.4.2
      # SSL issues :(
      #- test-mariadb-jruby-9.1.14.0:
      #    requires:
      #      - build-jruby-9.1.14.0
      - test-mysql-jruby-9.1.14.0:
          requires:
            - build-jruby-9.1.14.0
      - test-postgresql-jruby-9.1.14.0:
          requires:
            - build-jruby-9.1.14.0
